name: Scrape Diario de Ofertas

on:
  schedule:
    # SE EJECUTA CADA 8 HORAS (00:00, 08:00, 16:00)
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install scrapy psycopg2-binary python-dotenv

      - name: Ejecutar el Robot
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd backend
          echo "DATABASE_URL=$DATABASE_URL" > .env
          scrapy crawl job_spider
      - name: Enviar Newsletter
        env:
          # Pasamos las variables directamente al entorno
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          cd backend
          # Truco de seguridad: Forzamos la creacion de variables
          python mailer.py
